version: "3.9"

services:
  node_app:
    container_name: node_app
    build: .
    image: mohammadabuessa/node_live_app
    ports:
      - "8080:8080"
    environment:
      - PG_DB=node_live_db
      - PG_USER=abuessa
      - PG_PASSWORD=12345
      - PG_HOST=node_db
    depends_on:
      - node_db
  
  node_db:
    container_name: node_db
    image: postgres:12
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=node_live_db
      - POSTGRES_USER=abuessa
      - POSTGRES_PASSWORD=12345
    volumes:
      - node_db_data:/var/lib/postgresql/data

volumes:
  node_db_data: {}


